[project]
name = "log-analyzer"
version = "0.1.0"
description = "OTUS.Python Pro.HW#1"
authors = [
    {name = "v.yunusov",email = "v300187@yandex.ru"}
]
requires-python = ">=3.11"
dependencies = [
    "structlog (>=26.1.0,<27.0.0)",
    "pre-commit (>=4.6.2,<5.0.0)",
    "tqdm (>=4.70.1,<5.0.0)",
    "types-tqdm (>=4.70.0.20260906,<5.0.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
main-run = "log_analyzer.main:main"

[tool.mypy]
python_version = "3.11"
warn_return_any = true

[tool.ruff.lint]
ignore = ["E402"]

[dependency-groups]
dev = [
    "pytest (>=8.0.0,<9.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "ruff (>=0.16.6,<0.17.0)",
    "pre-commit (>=4.6.2,<5.0.0)",
    "mypy (>=2.3.1,<3.0.0)",
]
